"model":
  "type": "DFNet"
  "params":
    "in_channels": 4
    "hidden_channels": 64
    "L": 5
    "k": 12

"inference":
  "checkpoint_path": "checkpoints/checkpoint.tar"
  "image_size": !!python/tuple [640, 480]
  "cuda_id": 0
  "depth_min": 0.0
  "depth_max": 2.0
  "depth_norm": 1.0
